experimental_params:
  # Configuration for the experiment setup
  STREAM: True  # stream LSL data
  SCREEN: 0  # change if projecting to another PC 
  SCREEN_SIZE_HOME_PC: (1536, 864)
  SCREEN_WIDTH_HOME_PC: 35.94
  SCREEN_SIZE_LAB_PC: (1920, 1080)
  SCREEN_WIDTH_LAB_PC: 68.58  
  SCREEN_DISTANCE: 60.0
  SCREEN_COLOR: (0, 0, 0)
  FR: 60  # screen frame rate
  PR: 60  # codes presentation rate

  # Dimensions for various elements on the screen
  STT_WIDTH: 3  # adjust later
  STT_HEIGHT: 3  # 3 when used in lab monitorq
  TEXT_FIELD_HEIGHT: 3.0
  CIRCLE_WIDTH: 3.0
  CIRCLE_HEIGHT: 3.0


  # space between the two circles in visual degrees
  # Inner edge of left stimuli to inner edge of right stimuli
  SPACING_X: 4.2
  ANGLE_FROM_FIXATION: 0

  # background color of keys and shapes in sequence
  CIRCLE_COLORS:
    - black
    - white
  SHAPES:
    - r # rectangle
    - c # circle
    - i # inverted triangle
    - t # triangle
    - h # hourglass

  # Duration parameters (Total Duration  = n_runs x (run_wait_time + n_trials x (cue_time + trial_time + feedback_time + response_time + ITI_time))
  # number of runs for covert and overt conditions

  

  # Run wait time: 5s
  CUE_TIME: 1  # 1  #0.8
  TRIAL_TIME: 20  # 10 for overt// dk for covert, 5 reps
  RESPONSE_TIME: 5
  FEEDBACK_TIME: 1  # 0.5 -->  feedback is blue; cue is green
  ITI_TIME: 1  # 0.5

  # Number of trials 
  N_TRIALS: 20

analysis_params:
  CONDITIONS: ['overt', 'covert']
  CODE: 'mgold_61_6521_mod'
  N_SUBJECTS: 5
  N_CHANNELS: 64
  Fs: 120 # downsamping freq
  NUM_EVENTS: 3 # number of events (short, long and onset)
  N_RUNS_OVERT: 1
  N_RUNS_COVERT: 4

  # PATHS
  DATA_PATH: 'C:\Users\s1081686\Desktop\RA_Project\graz_conference\data\derivatives' # path to eeg preprocessed data
  CAPFILE_PATH: 'C:\Users\s1081686\Desktop\RA_Project\graz_conference\experiment\capfiles\biosemi64.loc' # path to the capfile

  # preprocessed eeg data filenames of all participants
  subjects_covert:
    - "pilot3_cvep_covert_mgold_61_6521_mod.npz"
    - "pilot4_cvep_covert_mgold_61_6521_mod.npz"
    - "pilot5_cvep_covert_mgold_61_6521_mod.npz"
    - "pilot6_cvep_covert_mgold_61_6521_mod.npz"
    - "pilot7_cvep_covert_mgold_61_6521_mod.npz"

  subjects_overt:
    - "pilot3_cvep_overt_mgold_61_6521_mod.npz"
    - "pilot4_cvep_overt_mgold_61_6521_mod.npz"
    - "pilot5_cvep_overt_mgold_61_6521_mod.npz"
    - "pilot6_cvep_overt_mgold_61_6521_mod.npz"
    - "pilot7_cvep_overt_mgold_61_6521_mod.npz"
